### ISSUE TITLE
Print stdout and stderr

### ISSUE THREAD

**Issue by wangjia184** [rchain-community/rchain.cloud#10]
Since version 0.3, powerbox is integrated which allows rholang contact to print messages to console via stdout and stderr.

One of the examples is here: https://github.com/rchain/rchain/blob/master/rholang/examples/stdout.rho

http://rchain.cloud/ should print the console messages

**Comment by tschoffelen** [comment]
Yes, this should work by default once we finish #9!

**Comment by tschoffelen** [comment]
#9 has been merged, and stdout and stderr are now being displayed.
